# Inherit from the common Open Source product configuration
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)

PRODUCT_NAME := omni_pmt3151
PRODUCT_DEVICE := pmt3151

PRODUCT_BRAND := PRESTIGIO
PRODUCT_MODEL := PMT3151
PRODUCT_MANUFACTURER := PRESTIGIO

PRODUCT_BUILD_PROP_OVERRIDES += \
    OMNI_DEVICE="PRESTIGIO_PMT3151"

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_NAME="PMT3151"

PRODUCT_BUILD_PROP_OVERRIDES += \
    BUILD_ID="PRESTIGIO_PMT3151" \
    BUILD_NUMBER="PMT3151" \
    BUILD_DISPLAY_ID="PMT3151"

PRODUCT_BUILD_PROP_OVERRIDES += \
    TARGET_BUILD_FLAVOR="PMT3151-$(TARGET_BUILD_VARIANT)"

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRIVATE_BUILD_DESC="PMT3151-$(TARGET_BUILD_VARIANT) 7.0 PRESTIGIO_PMT3151 0 test-keys"

BUILD_FINGERPRINT := PRESTIGIO/PMT3151/PRESTIGIO_PMT3151:7.0/PRESTIGIO_PMT3151/0:$(TARGET_BUILD_VARIANT)/test-keys

PRODUCT_GMS_CLIENTID_BASE := android-prestigio
